# Site settings
title: Jonathan Candelaria's Homepage
email: JECandelaria@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jecan.github.io/" # the base hostname & protocol for your site

# User setting
owner: Jonathan Candelaria
email: JECandelaria@gmail.com
facebook_username:
twitter_username:
github_username: JECan
address:
  - line: 873 Monarch Drive
  - line: Corona, CA 92879
  # Feel free to add more lines here 
telephone: (951)-284-5546
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
